version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.23.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../target/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe-simple-tasklist
    image: camunda/zeebe-simple-tasklist:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8081:8081"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
